"""
Generates tiny, heavily-blurred base64 JPEG placeholders (LQIP) for the
branch/interior photography, written out as a typed TS lookup map.

Run manually whenever images in src/assets/images change:
    python scripts/gen-blur-placeholders.py

This is a one-off dev-time generation script (not part of the Vite build),
which is why it lives outside src/ under scripts/.
"""

import base64
import io
import os

from PIL import Image, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGES_DIR = os.path.join(ROOT, "src", "assets", "images")
OUT_FILE = os.path.join(ROOT, "src", "assets", "blurPlaceholders.ts")

FILES = [
    "hero-indish.jpg",
    "kitwe-bar-lounge.jpg",
    "kitwe-dining.jpg",
    "kitwe-entrance.jpg",
    "kitwe-hall.jpg",
    "kitwe-lounge-seating.jpg",
    "lusaka-patio.jpg",
]

PLACEHOLDER_WIDTH = 28


def make_placeholder(path: str) -> str:
    with Image.open(path) as im:
        im = im.convert("RGB")
        ratio = PLACEHOLDER_WIDTH / im.width
        size = (PLACEHOLDER_WIDTH, max(1, round(im.height * ratio)))
        small = im.resize(size, Image.BILINEAR)
        small = small.filter(ImageFilter.GaussianBlur(radius=3))
        buf = io.BytesIO()
        small.save(buf, format="JPEG", quality=45)
        b64 = base64.b64encode(buf.getvalue()).decode("ascii")
        return f"data:image/jpeg;base64,{b64}"


def main():
    entries = []
    for name in FILES:
        path = os.path.join(IMAGES_DIR, name)
        if not os.path.exists(path):
            print(f"skip (not found): {name}")
            continue
        entries.append((name, make_placeholder(path)))
        print(f"generated: {name} ({len(entries[-1][1])} chars)")

    lines = [
        "// AUTO-GENERATED by scripts/gen-blur-placeholders.py — do not hand-edit.",
        "// Tiny blurred base64 placeholders (LQIP) keyed by source filename, used by",
        "// <BlurImage> for blur-up loading. Regenerate after changing branch photos.",
        "export const blurPlaceholders: Record<string, string> = {",
    ]
    for name, data in entries:
        lines.append(f'  "{name}": "{data}",')
    lines.append("};")
    lines.append("")

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"\nwrote {OUT_FILE}")


if __name__ == "__main__":
    main()
